<?php

namespace Onfan\UserBundle\Entity\User;

use Doctrine\ORM\EntityRepository;

/**
 * AccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessTokenRepository extends EntityRepository
{
}
